"""new fields in user model

Revision ID: 22908b6a339b
Revises: 633559feeac3
Create Date: 2020-11-11 17:44:46.740294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22908b6a339b'
down_revision = '633559feeac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
